wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Germany: "Europe/Berlin"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks A"
      type: "clocks"
    feedreader:
      enabled: true
      feeds:
      - https://brettterpstra.com/atom.xml
      # - http://thecellist-investment.blogspot.com/feeds/posts/default
      - http://www.markwk.com/atom.xml
      - https://onethingwell.org/rss
      - https://martinheinz.dev/rss/
      - https://victoria.dev/blog/index.xml
      # - https://www.streetsense.com.my/search/label/%E6%BD%AE%E6%B5%81
      - http://earlyretirementextreme.com/feed/rss
      # - http://wtfutil.com/blog/index.xml
      feedLimit: 10
      position:
        top: 1
        left: 0
        width: 2
        height: 1
      updateInterval: 14400
    cmder:
      args: [""]
      cmd: "/Users/yikkai95/Scripts/weekly-outcome.sh"
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    prettyweather:
      enabled: true
      city: "Johor Bahru"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 3600
    gcal:
      colors:
        title: "red"
        eventTime: "lightblue"
        description: "yellow"
        highlights:
        - ['Birthday', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "yikkai95@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal/credentials.json"
      showDeclined: true
